apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "bailer.bailerWorker.fullname" . }}
  labels:
{{ include "bailer.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.bailerWorker.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "bailer.name" . }}-worker
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "bailer.name" . }}-worker
{{ include "bailer.labels" . | indent 8 }}
    spec:
      serviceAccountName: {{ include "bailer.serviceAccount" . }}
      containers:
        - name: {{ include "bailer.bailerWorker.fullname" . }}
          image: "{{ .Values.bailer.image.repository }}:{{ .Values.bailer.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.bailer.image.pullPolicy }}
          args:
            - faktory
            - --config 
            - /etc/bailer/config.yaml 
            - --namespace 
            - {{ .Release.Namespace }}
            - --clusterauth
          env:
            - name: FAKTORY_URL
              value: {{ include "bailer.faktory.url" . }}
          resources:
{{ toYaml .Values.bailerWorker.resources | indent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/bailer/
      volumes:
        - name: config
          configMap:
            name: {{ include "bailer.fullname" . }}-config
    {{- with .Values.bailerWorker.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.bailerWorker.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.bailerWorker.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
