{{- if and .Values.faktory.enabled .Values.faktory.dash.enabled}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "bailer.faktory.fullname" . }}-dash
  labels:
{{ include "bailer.labels" . | indent 4 }}
{{- if .Values.faktory.dash.service.annotations }}
  annotations:
  {{- range $key, $val := .Values.faktory.dash.service.annotations }}
    {{ $key }}: {{ $val }}
  {{- end }}
{{- end }}
spec:
  type: {{ .Values.faktory.dash.service.type }}
  ports:
    {{- range .Values.faktory.dash.service.ports }} 
    - port: {{ . }}
      targetPort: http
      protocol: TCP
      name: http
    {{- end }}
  selector:
    app: {{ include "bailer.name" . }}-faktory
    release: {{ .Release.Name }}
{{- end }}
