{{- if .Values.faktory.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "bailer.fullname" . }}-faktory
  labels:
{{ include "bailer.labels" . | indent 4 }}
{{- if .Values.faktory.service.annotations }}
  annotations:
  {{- range $key, $val := .Values.faktory.service.annotations }}
    {{ $key }}: {{ $val }}
  {{- end }}
{{- end }}
spec:
  type: {{ .Values.faktory.service.type }}
  ports:
    - port: {{ .Values.faktory.service.port }}
      targetPort: tcp
      protocol: TCP
      name: tcp
  selector:
    app: {{ include "bailer.name" . }}-faktory
    release: {{ .Release.Name }}
{{- end }}
