{{- if .Values.faktory.enabled }}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "bailer.faktory.fullname" . }}
  labels:
{{ include "bailer.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "bailer.name" . }}-faktory
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "bailer.name" . }}-faktory
{{ include "bailer.labels" . | indent 8 }}
    spec:
      containers:
        - name: faktory
          image: "{{ .Values.faktory.image.repository }}:{{ .Values.faktory.image.tag }}"
          imagePullPolicy: {{ .Values.faktory.image.pullPolicy }}
          command:
            - /faktory
            - -b
            - :7419
            - -w
            - :7420
          ports:
            - name: tcp
              containerPort: 7419
              protocol: TCP
            - name: http
              containerPort: 7420
              protocol: TCP
          resources:
{{ toYaml .Values.faktory.resources | indent 12 }}
    {{- with .Values.faktory.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.faktory.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.faktory.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}
