{{- if .Values.faktory.dash.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "bailer.fullname" . }}-faktory-dash
  labels:
{{ include "bailer.labels" . | indent 4 }}
spec:
  type: {{ .Values.faktory.dash.service.type }}
  ports:
    - port: {{ .Values.faktory.dash.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "bailer.name" . }}-faktory
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
