apiVersion: v1
kind: Service
metadata:
  name: {{ template "bailer.fullname" . }}-faktory
  labels:
{{ include "bailer.labels" . | indent 4 }}
spec:
  type: {{ .Values.faktory.service.type }}
  ports:
    - port: {{ .Values.faktory.service.port }}
      targetPort: tcp
      protocol: TCP
      name: tcp
  selector:
    app.kubernetes.io/name: {{ include "bailer.name" . }}-faktory
    app.kubernetes.io/instance: {{ .Release.Name }}
