apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "bailer.fullname" . }}-faktory
  labels:
{{ include "bailer.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "bailer.name" . }}-faktory
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "bailer.name" . }}-faktory
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: faktory
          image: "{{ .Values.faktory.image.repository }}:{{ .Values.faktory.image.version }}"
          imagePullPolicy: {{ .Values.faktory.image.pullPolicy }}
          command:
            - /faktory
            - -b
            - :7419
          ports:
            - name: tcp
              containerPort: 7419 
              protocol: TCP
          resources:
{{ toYaml .Values.faktory.resources | indent 12 }}
    {{- with .Values.faktory.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.faktory.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.faktory.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
