{{- if .Values.rbac.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bailer.serviceAccount" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "bailer.labels" . | indent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "bailer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "bailer.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "bailer.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "bailer.serviceAccount" . }}
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "bailer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "bailer.labels" . | indent 4 }}
rules:
- apiGroups:
  - "batch"
  resources:
  - "jobs"
  verbs:
  - "create"
{{- end }}
