apiVersion: v1
kind: Service
metadata:
  name: {{ template "bailer.fullname" . }}
  labels:
{{ include "bailer.labels" . | indent 4 }}
{{- if .Values.bailer.service.annotations }}
  annotations:
  {{- range $key, $val := .Values.bailer.service.annotations }}
    {{ $key }}: {{ $val }}
  {{- end }}
{{- end }}
spec:
  type: {{ .Values.bailer.service.type }}
  ports:
    {{- range .Values.bailer.service.ports }}
    - port: {{ . }}
      targetPort: http
      protocol: TCP
      name: http
    {{- end }}
  selector:
    app: {{ include "bailer.name" . }}
    release: {{ .Release.Name }}
