bailers:
- alert: KubePodCrashLooping
  labels:
    namespace: default
    pod: ^nginx-.*
  serviceAccountName: bailer
  command:
    - /bin/bash
    - -c
    - "kubectl delete pod -n $ALERT_NAMESPACE $ALERT_POD"
  container:
    image: bitnami/kubectl
    tag: latest
